
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
#  - python .
<<<<<<< HEAD
  python userlist.py test
=======
  python userlist.py test
>>>>>>> origin/master
