
language: python
python:
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install edgegrid-python
  
script:
#  - python .
  python userlist.py test

